/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResignationRouteImport } from './routes/resignation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PayslipsRouteImport } from './routes/payslips'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as MonthlyAttendanceRouteImport } from './routes/monthly-attendance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DevResetRouteImport } from './routes/dev-reset'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResignationRoute = ResignationRouteImport.update({
  id: '/resignation',
  path: '/resignation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipsRoute = PayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyAttendanceRoute = MonthlyAttendanceRouteImport.update({
  id: '/monthly-attendance',
  path: '/monthly-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DevResetRoute = DevResetRouteImport.update({
  id: '/dev-reset',
  path: '/dev-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/dev-reset': typeof DevResetRoute
  '/directory': typeof DirectoryRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/kiosk': typeof KioskRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/monthly-attendance': typeof MonthlyAttendanceRoute
  '/payroll': typeof PayrollRoute
  '/payslips': typeof PayslipsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation': typeof ResignationRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/dev-reset': typeof DevResetRoute
  '/directory': typeof DirectoryRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/kiosk': typeof KioskRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/monthly-attendance': typeof MonthlyAttendanceRoute
  '/payroll': typeof PayrollRoute
  '/payslips': typeof PayslipsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation': typeof ResignationRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/dev-reset': typeof DevResetRoute
  '/directory': typeof DirectoryRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/kiosk': typeof KioskRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/monthly-attendance': typeof MonthlyAttendanceRoute
  '/payroll': typeof PayrollRoute
  '/payslips': typeof PayslipsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation': typeof ResignationRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/dashboard'
    | '/dev-reset'
    | '/directory'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/holidays'
    | '/kiosk'
    | '/leaves'
    | '/login'
    | '/monthly-attendance'
    | '/payroll'
    | '/payslips'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/resignation'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/dashboard'
    | '/dev-reset'
    | '/directory'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/holidays'
    | '/kiosk'
    | '/leaves'
    | '/login'
    | '/monthly-attendance'
    | '/payroll'
    | '/payslips'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/resignation'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/dashboard'
    | '/dev-reset'
    | '/directory'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/holidays'
    | '/kiosk'
    | '/leaves'
    | '/login'
    | '/monthly-attendance'
    | '/payroll'
    | '/payslips'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/resignation'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  DevResetRoute: typeof DevResetRoute
  DirectoryRoute: typeof DirectoryRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  HolidaysRoute: typeof HolidaysRoute
  KioskRoute: typeof KioskRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  MonthlyAttendanceRoute: typeof MonthlyAttendanceRoute
  PayrollRoute: typeof PayrollRoute
  PayslipsRoute: typeof PayslipsRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResignationRoute: typeof ResignationRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resignation': {
      id: '/resignation'
      path: '/resignation'
      fullPath: '/resignation'
      preLoaderRoute: typeof ResignationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslips': {
      id: '/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof PayslipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-attendance': {
      id: '/monthly-attendance'
      path: '/monthly-attendance'
      fullPath: '/monthly-attendance'
      preLoaderRoute: typeof MonthlyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-reset': {
      id: '/dev-reset'
      path: '/dev-reset'
      fullPath: '/dev-reset'
      preLoaderRoute: typeof DevResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  DevResetRoute: DevResetRoute,
  DirectoryRoute: DirectoryRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  HolidaysRoute: HolidaysRoute,
  KioskRoute: KioskRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  MonthlyAttendanceRoute: MonthlyAttendanceRoute,
  PayrollRoute: PayrollRoute,
  PayslipsRoute: PayslipsRoute,
  PerformanceRoute: PerformanceRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResignationRoute: ResignationRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
